apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-nginx
  template:
    metadata:
      labels:
        app: crud-nginx
    spec:
      containers:
        - name: crud-nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

